import { z } from "zod";
import { SourceIdSchema } from "./ids.ts";

/**
 * Transaction-monitoring alert. Generated by deterministic rules over the real
 * transaction data (data/overlay/build-overlay.ts), never invented outright —
 * see the plan's "Honest gaps" section.
 */
export const AlertSchema = z.object({
  sourceId: SourceIdSchema,
  alertId: z.string(),
  accountId: z.string(),
  ruleId: z.string(),
  ruleVersion: z.string(),
  firedAt: z.string(),
  jurisdiction: z.string(),
  dueDate: z.string(),
  sarConfidentialitySensitive: z.boolean(),
});
export type Alert = z.infer<typeof AlertSchema>;
